export const BOOK_NAMES: string[] = [
  "", // 0 unused — 1-indexed
  "Genesis",
  "Exodus",
  "Leviticus",
  "Numbers",
  "Deuteronomy",
  "Joshua",
  "Judges",
  "Ruth",
  "1 Samuel",
  "2 Samuel",
  "1 Kings",
  "2 Kings",
  "1 Chronicles",
  "2 Chronicles",
  "Ezra",
  "Nehemiah",
  "Esther",
  "Job",
  "Psalms",
  "Proverbs",
  "Ecclesiastes",
  "Song of Solomon",
  "Isaiah",
  "Jeremiah",
  "Lamentations",
  "Ezekiel",
  "Daniel",
  "Hosea",
  "Joel",
  "Amos",
  "Obadiah",
  "Jonah",
  "Micah",
  "Nahum",
  "Habakkuk",
  "Zephaniah",
  "Haggai",
  "Zechariah",
  "Malachi",
  "Matthew",
  "Mark",
  "Luke",
  "John",
  "Acts",
  "Romans",
  "1 Corinthians",
  "2 Corinthians",
  "Galatians",
  "Ephesians",
  "Philippians",
  "Colossians",
  "1 Thessalonians",
  "2 Thessalonians",
  "1 Timothy",
  "2 Timothy",
  "Titus",
  "Philemon",
  "Hebrews",
  "James",
  "1 Peter",
  "2 Peter",
  "1 John",
  "2 John",
  "3 John",
  "Jude",
  "Revelation",
];

/** Abbreviation → book number mapping (lowercase keys). */
export const BOOK_ABBREVS: Record<string, number> = {
  // OT
  genesis: 1,
  gen: 1,
  ge: 1,
  exodus: 2,
  exo: 2,
  ex: 2,
  leviticus: 3,
  lev: 3,
  le: 3,
  numbers: 4,
  num: 4,
  nu: 4,
  deuteronomy: 5,
  deut: 5,
  de: 5,
  dt: 5,
  joshua: 6,
  josh: 6,
  jos: 6,
  judges: 7,
  judg: 7,
  jdg: 7,
  ruth: 8,
  ru: 8,
  "1 samuel": 9,
  "1samuel": 9,
  "1sam": 9,
  "1sa": 9,
  "2 samuel": 10,
  "2samuel": 10,
  "2sam": 10,
  "2sa": 10,
  "1 kings": 11,
  "1kings": 11,
  "1ki": 11,
  "1kgs": 11,
  "2 kings": 12,
  "2kings": 12,
  "2ki": 12,
  "2kgs": 12,
  "1 chronicles": 13,
  "1chronicles": 13,
  "1chr": 13,
  "1ch": 13,
  "2 chronicles": 14,
  "2chronicles": 14,
  "2chr": 14,
  "2ch": 14,
  ezra: 15,
  ezr: 15,
  nehemiah: 16,
  neh: 16,
  ne: 16,
  esther: 17,
  esth: 17,
  es: 17,
  job: 18,
  jb: 18,
  psalms: 19,
  psalm: 19,
  psa: 19,
  ps: 19,
  proverbs: 20,
  prov: 20,
  pro: 20,
  pr: 20,
  ecclesiastes: 21,
  eccl: 21,
  ecc: 21,
  ec: 21,
  "song of solomon": 22,
  "song of songs": 22,
  song: 22,
  sos: 22,
  ss: 22,
  isaiah: 23,
  isa: 23,
  jeremiah: 24,
  jer: 24,
  je: 24,
  lamentations: 25,
  lam: 25,
  la: 25,
  ezekiel: 26,
  ezek: 26,
  eze: 26,
  daniel: 27,
  dan: 27,
  da: 27,
  dn: 27,
  hosea: 28,
  hos: 28,
  ho: 28,
  joel: 29,
  joe: 29,
  jl: 29,
  amos: 30,
  am: 30,
  obadiah: 31,
  oba: 31,
  ob: 31,
  jonah: 32,
  jon: 32,
  micah: 33,
  mic: 33,
  mi: 33,
  nahum: 34,
  nah: 34,
  na: 34,
  habakkuk: 35,
  hab: 35,
  zephaniah: 36,
  zeph: 36,
  zep: 36,
  haggai: 37,
  hag: 37,
  zechariah: 38,
  zech: 38,
  zec: 38,
  malachi: 39,
  mal: 39,
  // NT
  matthew: 40,
  matt: 40,
  mat: 40,
  mt: 40,
  mark: 41,
  mrk: 41,
  mk: 41,
  mr: 41,
  luke: 42,
  luk: 42,
  lk: 42,
  john: 43,
  joh: 43,
  jn: 43,
  acts: 44,
  ac: 44,
  romans: 45,
  rom: 45,
  ro: 45,
  "1 corinthians": 46,
  "1corinthians": 46,
  "1cor": 46,
  "1co": 46,
  "2 corinthians": 47,
  "2corinthians": 47,
  "2cor": 47,
  "2co": 47,
  galatians: 48,
  gal: 48,
  ga: 48,
  ephesians: 49,
  eph: 49,
  philippians: 50,
  phil: 50,
  php: 50,
  colossians: 51,
  col: 51,
  "1 thessalonians": 52,
  "1thessalonians": 52,
  "1thess": 52,
  "1th": 52,
  "2 thessalonians": 53,
  "2thessalonians": 53,
  "2thess": 53,
  "2th": 53,
  "1 timothy": 54,
  "1timothy": 54,
  "1tim": 54,
  "1ti": 54,
  "2 timothy": 55,
  "2timothy": 55,
  "2tim": 55,
  "2ti": 55,
  titus: 56,
  tit: 56,
  philemon: 57,
  philem: 57,
  phm: 57,
  hebrews: 58,
  heb: 58,
  james: 59,
  jas: 59,
  jm: 59,
  "1 peter": 60,
  "1peter": 60,
  "1pet": 60,
  "1pe": 60,
  "2 peter": 61,
  "2peter": 61,
  "2pet": 61,
  "2pe": 61,
  "1 john": 62,
  "1john": 62,
  "1joh": 62,
  "1jn": 62,
  "2 john": 63,
  "2john": 63,
  "2joh": 63,
  "2jn": 63,
  "3 john": 64,
  "3john": 64,
  "3joh": 64,
  "3jn": 64,
  jude: 65,
  jud: 65,
  revelation: 66,
  rev: 66,
  re: 66,
};

/** Parse "Book Chapter:Verse" (with abbreviation support). Returns null on failure. */
export function parseRef(
  input: string,
): { book: number; chapter: number; verse: number } | null {
  const trimmed = input.trim().toLowerCase();
  if (!trimmed) return null;

  // Sort by length desc so "1 samuel" matches before "1sa" would shadow "sa"
  const sorted = Object.entries(BOOK_ABBREVS).sort(
    (a, b) => b[0].length - a[0].length,
  );

  let foundBook = 0;
  let rest = "";

  for (const [abbrev, num] of sorted) {
    if (trimmed.startsWith(abbrev)) {
      // Make sure what follows is whitespace/digit, not another letter
      const after = trimmed[abbrev.length];
      if (after === undefined || /[\s\d]/.test(after)) {
        foundBook = num;
        rest = trimmed.slice(abbrev.length).trim();
        break;
      }
    }
  }

  if (!foundBook) return null;

  const colonMatch = rest.match(/^(\d+)[:\s](\d+)$/);
  if (colonMatch) {
    return {
      book: foundBook,
      chapter: Number(colonMatch[1]),
      verse: Number(colonMatch[2]),
    };
  }
  const chapOnly = rest.match(/^(\d+)$/);
  if (chapOnly) {
    return { book: foundBook, chapter: Number(chapOnly[1]), verse: 1 };
  }
  return null;
}
